name: Daily Log

on:
  workflow_dispatch:
  schedule:
    - cron: '50 23 * * *'  # Run every day at midnight (UTC)
env:
  CLIENT_ID: ${{ secrets.WT_API }}
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
  
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Replace with the desired Python version

#       - name: Set up Google Cloud SDK
#         uses: google-github-actions/setup-gcloud@v0.4.3
#         with:
#           service_account_key: ${{ secrets.GCP_SA_KEY }}
#           project_id: wakatime-stats

      - name: Set up Google Cloud SDK
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
        
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python daily.py
